#!/usr/bin/env python

import sys
from simphtml import parse

if __name__ == '__main__':
	if len(sys.argv) != 2:
		print 'Usage: %s <file>.html'
		sys.exit(1)

	try:
		with file(sys.argv[1]) as f:
			ast = parse(f)
		print ast
	except ParseError as e:
		print 'Problem parsing the input file:', e
		sys.exit(1)
	except TokenizeError as e:
		print 'Problem tokenizing the input file:', e
		sys.exit(1)
