#!/usr/bin/env python

import unittest
import simphtml.test

if __name__ == '__main__':
	suite = unittest.TestLoader().loadTestsFromModule(simphtml.test)
	unittest.TextTestRunner(verbosity=2).run(suite)
