#!/usr/bin/env python

import unittest
import simphtml

class TestIsValid(unittest.TestCase):
	def test_empty(self):
		self.assertTrue(simphtml.isValid(''))

if __name__ == '__main__':
	unittest.main()
